# PSQL role settings
postgresql_service_enabled: true
postgresql_pg_hba_md5_hosts:
  - "172.16.137.102/32"
  - "172.16.137.103/32"
postgresql_pg_hba_custom:
  - type: host
    database: replication
    user: "repl"
    address: "172.16.137.102/32"
    method: md5
  - type: host
    database: replication
    user: "repl"
    address: "172.16.137.103/32"
    method: md5
postgresql_shared_preload_libraries:
  - timescaledb
postgresql_wal_level: "replica"
postgresql_max_wal_senders: 5
postgresql_max_replication_slots: 5
postgresql_listen_addresses:
  - "*"
postgresql_version: 11
postgresql_users:
  - name: "app"
    pass: "P@ssW0rdl"
    encrypted: yes
  - name: "repl"
    pass: "Dr0w55@p"
    encrypted: yes
postgresql_databases:
  - name: "appdb"
    owner: "app"
postgresql_user_privileges:
  - name: "app"
    db: "appdb"
    priv: "ALL"
    role_attr_flags: "SUPERUSER"
  - name: "repl"
    role_attr_flags: "REPLICATION"
